# Generated by Django 2.0.7 on 2018-07-31 17:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipping', models.IntegerField(unique=True, verbose_name='Tombamento')),
                ('status', models.BooleanField(verbose_name='Disponibilidade')),
                ('type', models.IntegerField(verbose_name='Tipo')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notas')),
                ('hdmi', models.BooleanField(verbose_name='HDMI')),
                ('vga', models.BooleanField(verbose_name='VGA')),
            ],
            options={
                'verbose_name': 'Projetor',
                'verbose_name_plural': 'Projetores',
            },
        ),
    ]
