# Generated by Django 2.0.7 on 2018-08-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0003_auto_20180807_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projector',
            name='hdmi',
        ),
        migrations.RemoveField(
            model_name='projector',
            name='vga',
        ),
        migrations.AddField(
            model_name='projector',
            name='cable',
            field=models.CharField(choices=[('HDMI', 'HDMI'), ('VGA', 'VGA')], default='VGA', max_length=4, verbose_name='Tipo'),
        ),
    ]
